steps:
  - name : 'python'
    entrypoint: 'bash'
    args: 
      - '-c' 
      - |
            echo "PROJ_ID: $PROJECT_ID starting and executing my_strcmp.py"
            python my_strcmp.py sunny
            echo "completed my_strcmp.py"

options:
  logging: CLOUD_LOGGING_ONLY

#timeout: "440s"